name: Update Waka Chart

on:
  schedule:
    - cron: '0 */6 * * *' # Executing every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch All-Time WakaTime Data
        env:
          WAKA_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          AUTH=$(echo -n "$WAKA_KEY" | base64)
          
          curl -H "Authorization: Basic $AUTH" \
          "https://wakatime.com/api/v1/users/current/stats/all_time" \
          -o wakatime-chart.json

      - name: Commit and Push JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wakatime-chart.json
          git commit -m "Update All-Time WakaTime stats" || exit 0
          git push
